[versions]
kotlin = "1.6.10"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version = "1.6.0" }
chrome = { module = "com.github.AndrewReitz:chrome-extension-kotlin-api", version = "main-SNAPSHOT" }
html = { module = "org.jetbrains.kotlinx:kotlinx-html-js", version = "0.7.3"}

[bundles]
extension = ["coroutines", "chrome"]
